#!/usr/bin/env python3
"""
Hermes Trading System - Smart Model Routing
AUTO-GENERATED by daily_model_scanner.py
Last updated: 2026-05-24T00:56:52.687571
"""
import os
import json
import logging
from datetime import datetime
from dotenv import load_dotenv

load_dotenv("/home/r00t/hermes-trading/config/.env")
logger = logging.getLogger(__name__)

# === AUTO-GENERATED MODEL REGISTRY ===
MODELS = {
    "or": [
        {
            "id": "baidu/cobuddy:free",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
            "ctx": 256000,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning"
            ]
        },
        {
            "id": "poolside/laguna-xs.2:free",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "poolside/laguna-m.1:free",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "deepseek/deepseek-v4-flash:free",
            "ctx": 1048576,
            "tools": true,
            "speed": "slow",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "google/gemma-4-26b-a4b-it:free",
            "ctx": 262144,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "google/gemma-4-31b-it:free",
            "ctx": 262144,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "arcee-ai/trinity-large-thinking:free",
            "ctx": 262144,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning"
            ]
        },
        {
            "id": "nvidia/nemotron-3-super-120b-a12b:free",
            "ctx": 1000000,
            "tools": true,
            "speed": "slow",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "minimax/minimax-m2.5:free",
            "ctx": 204800,
            "tools": true,
            "speed": "medium",
            "task": [
                "light"
            ]
        },
        {
            "id": "liquid/lfm-2.5-1.2b-thinking:free",
            "ctx": 32768,
            "tools": false,
            "speed": "fast",
            "task": [
                "reasoning"
            ]
        },
        {
            "id": "liquid/lfm-2.5-1.2b-instruct:free",
            "ctx": 32768,
            "tools": false,
            "speed": "fast",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "nvidia/nemotron-3-nano-30b-a3b:free",
            "ctx": 256000,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/nemotron-nano-12b-v2-vl:free",
            "ctx": 128000,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "qwen/qwen3-next-80b-a3b-instruct:free",
            "ctx": 262144,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "nvidia/nemotron-nano-9b-v2:free",
            "ctx": 128000,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "openai/gpt-oss-120b:free",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "openai/gpt-oss-20b:free",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "z-ai/glm-4.5-air:free",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "qwen/qwen3-coder:free",
            "ctx": 1048576,
            "tools": true,
            "speed": "slow",
            "task": [
                "coding"
            ]
        },
        {
            "id": "cognitivecomputations/dolphin-mistral-24b-venice-edition:free",
            "ctx": 32768,
            "tools": false,
            "speed": "fast",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "meta-llama/llama-3.3-70b-instruct:free",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "meta-llama/llama-3.2-3b-instruct:free",
            "ctx": 131072,
            "tools": false,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "nousresearch/hermes-3-llama-3.1-405b:free",
            "ctx": 131072,
            "tools": false,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        }
    ],
    "groq": [
        {
            "id": "whisper-large-v3",
            "ctx": 131072,
            "tools": true,
            "speed": "fast",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "llama-3.1-8b-instant",
            "ctx": 131072,
            "tools": true,
            "speed": "fast",
            "task": [
                "light"
            ]
        },
        {
            "id": "meta-llama/llama-4-scout-17b-16e-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "fast",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "allam-2-7b",
            "ctx": 131072,
            "tools": true,
            "speed": "fast",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "canopylabs/orpheus-arabic-saudi",
            "ctx": 131072,
            "tools": true,
            "speed": "fast",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "qwen/qwen3-32b",
            "ctx": 131072,
            "tools": true,
            "speed": "fast",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "meta-llama/llama-prompt-guard-2-86m",
            "ctx": 131072,
            "tools": true,
            "speed": "fast",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "llama-3.3-70b-versatile",
            "ctx": 131072,
            "tools": true,
            "speed": "fast",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "openai/gpt-oss-20b",
            "ctx": 131072,
            "tools": true,
            "speed": "fast",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "openai/gpt-oss-120b",
            "ctx": 131072,
            "tools": true,
            "speed": "fast",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "whisper-large-v3-turbo",
            "ctx": 131072,
            "tools": true,
            "speed": "fast",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "meta-llama/llama-prompt-guard-2-22m",
            "ctx": 131072,
            "tools": true,
            "speed": "fast",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "groq/compound",
            "ctx": 131072,
            "tools": true,
            "speed": "fast",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "groq/compound-mini",
            "ctx": 131072,
            "tools": true,
            "speed": "fast",
            "task": [
                "light"
            ]
        },
        {
            "id": "canopylabs/orpheus-v1-english",
            "ctx": 131072,
            "tools": true,
            "speed": "fast",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "openai/gpt-oss-safeguard-20b",
            "ctx": 131072,
            "tools": true,
            "speed": "fast",
            "task": [
                "reasoning",
                "analysis"
            ]
        }
    ],
    "nvidia": [
        {
            "id": "01-ai/yi-large",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "abacusai/dracarys-llama-3.1-70b-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "adept/fuyu-8b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "light"
            ]
        },
        {
            "id": "ai21labs/jamba-1.5-large-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "aisingapore/sea-lion-7b-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "baai/bge-m3",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "bigcode/starcoder2-15b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "coding"
            ]
        },
        {
            "id": "bytedance/seed-oss-36b-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "databricks/dbrx-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "deepseek-ai/deepseek-coder-6.7b-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "coding",
                "analysis"
            ]
        },
        {
            "id": "deepseek-ai/deepseek-v4-flash",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "deepseek-ai/deepseek-v4-flash",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "deepseek-ai/deepseek-v4-pro",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "deepseek-ai/deepseek-v4-pro",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "google/codegemma-1.1-7b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "coding"
            ]
        },
        {
            "id": "google/codegemma-7b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "coding"
            ]
        },
        {
            "id": "google/deplot",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "google/gemma-2-2b-it",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "google/gemma-2b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "google/gemma-3-12b-it",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "google/gemma-3-4b-it",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "google/gemma-3n-e2b-it",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "google/gemma-3n-e4b-it",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "google/gemma-4-31b-it",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "google/recurrentgemma-2b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "ibm/granite-3.0-3b-a800m-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "ibm/granite-3.0-8b-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis",
                "light"
            ]
        },
        {
            "id": "ibm/granite-34b-code-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "coding",
                "analysis"
            ]
        },
        {
            "id": "ibm/granite-8b-code-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "coding",
                "analysis",
                "light"
            ]
        },
        {
            "id": "meta/codellama-70b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "coding"
            ]
        },
        {
            "id": "meta/llama-3.1-70b-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "meta/llama-3.1-8b-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis",
                "light"
            ]
        },
        {
            "id": "meta/llama-3.2-11b-vision-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "meta/llama-3.2-1b-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "meta/llama-3.2-3b-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "meta/llama-3.2-90b-vision-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "meta/llama-3.3-70b-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "meta/llama-4-maverick-17b-128e-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "meta/llama-guard-4-12b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "meta/llama2-70b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "microsoft/kosmos-2",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "microsoft/phi-3-vision-128k-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "microsoft/phi-3.5-moe-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "microsoft/phi-4-mini-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis",
                "light"
            ]
        },
        {
            "id": "microsoft/phi-4-multimodal-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "minimaxai/minimax-m2.7",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "light"
            ]
        },
        {
            "id": "mistralai/codestral-22b-instruct-v0.1",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "coding",
                "analysis"
            ]
        },
        {
            "id": "mistralai/ministral-14b-instruct-2512",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis",
                "light"
            ]
        },
        {
            "id": "mistralai/mistral-7b-instruct-v0.3",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "mistralai/mistral-large",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "mistralai/mistral-large-2-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "mistralai/mistral-large-3-675b-instruct-2512",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "mistralai/mistral-medium-3.5-128b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "light"
            ]
        },
        {
            "id": "mistralai/mistral-nemotron",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "mistralai/mistral-small-4-119b-2603",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "light"
            ]
        },
        {
            "id": "mistralai/mixtral-8x22b-v0.1",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "mistralai/mixtral-8x7b-instruct-v0.1",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "moonshotai/kimi-k2.6",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nv-mistralai/mistral-nemo-12b-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "nvidia/ai-synthetic-video-detector",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/cosmos-reason2-8b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "light"
            ]
        },
        {
            "id": "nvidia/embed-qa-4",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/gliner-pii",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/ising-calibration-1-35b-a3b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/llama-3.1-nemoguard-8b-content-safety",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "light"
            ]
        },
        {
            "id": "nvidia/llama-3.1-nemoguard-8b-topic-control",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "light"
            ]
        },
        {
            "id": "nvidia/llama-3.1-nemotron-51b-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "nvidia/llama-3.1-nemotron-70b-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "nvidia/llama-3.1-nemotron-nano-8b-v1",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "light"
            ]
        },
        {
            "id": "nvidia/llama-3.1-nemotron-nano-vl-8b-v1",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "light"
            ]
        },
        {
            "id": "nvidia/llama-3.1-nemotron-safety-guard-8b-v3",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "light"
            ]
        },
        {
            "id": "nvidia/llama-3.1-nemotron-ultra-253b-v1",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/llama-3.2-nemoretriever-1b-vlm-embed-v1",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/llama-3.2-nv-embedqa-1b-v1",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/llama-3.3-nemotron-super-49b-v1",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/llama-3.3-nemotron-super-49b-v1.5",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/llama-nemotron-embed-1b-v2",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/llama-nemotron-embed-vl-1b-v2",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/llama3-chatqa-1.5-70b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "nvidia/mistral-nemo-minitron-8b-8k-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis",
                "light"
            ]
        },
        {
            "id": "nvidia/nemoretriever-parse",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/nemotron-3-content-safety",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/nemotron-3-nano-30b-a3b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning"
            ]
        },
        {
            "id": "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning"
            ]
        },
        {
            "id": "nvidia/nemotron-3-super-120b-a12b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/nemotron-3-super-120b-a12b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/nemotron-4-340b-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "nvidia/nemotron-4-340b-reward",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/nemotron-content-safety-reasoning-4b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning"
            ]
        },
        {
            "id": "nvidia/nemotron-mini-4b-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis",
                "light"
            ]
        },
        {
            "id": "nvidia/nemotron-nano-12b-v2-vl",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/nemotron-nano-3-30b-a3b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/nemotron-parse",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/neva-22b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/nv-embed-v1",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/nv-embedcode-7b-v1",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "coding"
            ]
        },
        {
            "id": "nvidia/nv-embedqa-e5-v5",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/nv-embedqa-mistral-7b-v2",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/nvclip",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/nvidia-nemotron-nano-9b-v2",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "nvidia/riva-translate-4b-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "nvidia/riva-translate-4b-instruct-v1.1",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "nvidia/vila",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "openai/gpt-oss-120b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "openai/gpt-oss-120b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "openai/gpt-oss-20b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "openai/gpt-oss-20b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "qwen/qwen3-coder-480b-a35b-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "coding",
                "analysis"
            ]
        },
        {
            "id": "qwen/qwen3-next-80b-a3b-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "qwen/qwen3.5-122b-a10b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "qwen/qwen3.5-397b-a17b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "sarvamai/sarvam-m",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "snowflake/arctic-embed-l",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "stepfun-ai/step-3.5-flash",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "stockmark/stockmark-2-100b-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "upstage/solar-10.7b-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        },
        {
            "id": "writer/palmyra-creative-122b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "writer/palmyra-fin-70b-32k",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "writer/palmyra-med-70b",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "writer/palmyra-med-70b-32k",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "z-ai/glm-5.1",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "reasoning",
                "analysis"
            ]
        },
        {
            "id": "zyphra/zamba2-7b-instruct",
            "ctx": 131072,
            "tools": true,
            "speed": "medium",
            "task": [
                "analysis"
            ]
        }
    ]
}

# === TASK-TO-MODEL MAPPING ===
TASK_MODEL_MAP = {
    "coding": ["groq/compound-mini", "qwen/qwen3-coder:free", "openai/gpt-oss-120b:free"],
    "analysis": ["llama-3.3-70b-versatile", "deepseek/deepseek-v4-flash:free", "nvidia/nemotron-3-super-120b-a12b:free"],
    "reasoning": ["deepseek/deepseek-v4-flash:free", "nvidia/nemotron-3-super-120b-a12b:free", "llama-3.3-70b-versatile"],
    "light": ["llama-3.1-8b-instant", "groq/compound-mini", "openai/gpt-oss-20b:free"],
}


class SmartModelRouter:
    """Inteligentny router modeli AI"""
    
    def __init__(self):
        self.MODELS = MODELS
        self.TASK_MODEL_MAP = TASK_MODEL_MAP
        self.stats = {p: {"requests": 0, "errors": 0, "total_time": 0} for p in MODELS}
    
    def get_model_for_task(self, task_type="reasoning", prefer_speed=False):
        """Wybierz najlepszy model dla danego zadania"""
        candidates = self.TASK_MODEL_MAP.get(task_type, self.TASK_MODEL_MAP["reasoning"])
        
        for model_id in candidates:
            for provider, config in self.MODELS.items():
                for m in config:
                    if m["id"] == model_id:
                        errors = self.stats[provider]["errors"]
                        if errors < 3:
                            return {
                                "model": model_id,
                                "provider": provider,
                                "config": config,
                                "ctx": m["ctx"],
                                "tools": m["tools"],
                            }
        
        # Fallback
        for provider, config in self.MODELS.items():
            for m in config:
                return {"model": m["id"], "provider": provider, "config": config, "ctx": m["ctx"], "tools": m["tools"]}
        return None
    
    def record_result(self, provider, success, elapsed):
        self.stats[provider]["requests"] += 1
        if not success:
            self.stats[provider]["errors"] += 1
        self.stats[provider]["total_time"] += elapsed
    
    def get_stats(self):
        return self.stats


router = SmartModelRouter()


def get_model(task_type="reasoning", prefer_speed=False):
    return router.get_model_for_task(task_type, prefer_speed)
